// src/routes/index.ts
import express from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import userRoutes from '../modules/user/user.routes.js';
import statusRoutes from './health.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import conversationRoutes from '../modules/conversation/conversation.routes.js';
import fileRoutes from '../modules/file/file.routes.js';
import visionRoutes from '../modules/vision/vision.routes.js';
import llmRoutes from '../modules/llm/llm.routes.js';
// Phase 4 routes
import queueRoutes from './queue.routes.js';
import monitoringRoutes from './monitoring.routes.js';
import chatRoutes from './chat.routes.js';
import templateRoutes from '../modules/template/template.routes.js';
import toolRoutes from '../modules/tool/tool.routes.js';

const router = express.Router();

// Mount individual routers
router.use('/auth', authRoutes);     // Routes for /api/auth/...
router.use('/user', userRoutes);     // Routes for /api/user/...
router.use('/status', statusRoutes); // Routes for /api/status/...
router.use('/admin', adminRoutes);   // Routes for /api/admin/...
router.use('/conversations', conversationRoutes); // Routes for /api/conversations/...
router.use('/files', fileRoutes);     // Routes for /api/files/...
router.use('/vision', visionRoutes);   // Routes for /api/vision/...
router.use('/llm', llmRoutes);         // Routes for /api/llm/...
router.use('/chat', chatRoutes);     // Routes for /api/chat/... (Mobile/HTTP)
router.use('/templates', templateRoutes); // Routes for /api/templates/...
router.use('/tools', toolRoutes);     // Routes for /api/tools/...

// Phase 4 routes
router.use('/queue', queueRoutes);         // Routes for /api/queue/...
router.use('/monitoring', monitoringRoutes); // Routes for /api/monitoring/...

// Stage 1: Session routes
import sessionRoutes from '../modules/session/session.routes.js';
router.use('/session', sessionRoutes);     // Routes for /api/session/...

// Stage 7: Advanced Features
import searchRoutes from '../modules/search/search.routes.js';
import plannerRoutes from '../modules/planner/planner.routes.js';
import memoryRoutes from '../modules/memory/memory.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import feedbackRoutes from './feedback.routes.js'; // STAGE 21
import shareRoutes from './share.routes.js'; // STAGE 22
import modelRoutes from './model.routes.js'; // STAGE 23
import conversationTemplateRoutes from './template.routes.js'; // STAGE 24
import folderRoutes from './folder.routes.js'; // STAGE 26
import pluginRoutes from './plugin.routes.js'; // STAGE 28

router.use('/search', searchRoutes);       // Routes for /api/search/...
router.use('/planner', plannerRoutes);     // Routes for /api/planner/...
router.use('/memory', memoryRoutes);       // Routes for /api/memory/...
router.use('/analytics', analyticsRoutes); // Routes for /api/analytics/...
router.use('/feedback', feedbackRoutes);   // STAGE 21: Routes for /api/feedback/...
router.use('/share', shareRoutes);         // STAGE 22: Routes for /api/share/...
router.use('/conversations', modelRoutes); // STAGE 23: Routes for /api/conversations/:id/model
router.use('/conversations', conversationTemplateRoutes); // STAGE 24: Routes for /api/conversations/:id/template
router.use('/folders', folderRoutes);      // STAGE 26: Routes for /api/folders/...
router.use('/plugins', pluginRoutes);      // STAGE 28: Routes for /api/plugins/...

export default router;

