// Defines custom error codes and messages
export const ERROR_CODES = {
    UNAUTHORIZED: 'AUTH_001',
    INVALID_INPUT: 'VALIDATION_001',
    NOT_FOUND: 'RESOURCE_001',
    INTERNAL_SERVER_ERROR: 'SERVER_001',
    DB_ERROR: 'DB_001',
    SERVICE_UNAVAILABLE: 'SERVICE_001',
    PYTHON_SCRIPT_ERROR: 'PYTHON_001',
};